Analyse exploratoire préliminaire

 Pour assurer la reproductibilité de ton projet, les fichiers sont télécharger avec des chemins dynamiques.

In [38]:
import os
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display
%matplotlib inline

 # Pour remonter d'un dossier pour le notebook
 # afin d'assurer une meilleure reproductibilité
base_path = os.path.abspath("..") 
data_path = os.path.join(base_path, "data")

X_train = pd.read_csv(os.path.join(data_path, 
                                   "X_train_update.csv"), 
                                   index_col=0)
X_test = pd.read_csv(os.path.join(data_path, 
                                  "X_test_update.csv"), 
                                  index_col=0)
Y_train = pd.read_csv(os.path.join(data_path, 
                                   "Y_train_CVw08PX.csv"), 
                                   index_col=0)
pd.set_option('display.max_colwidth', 25) 
display(X_train.head())

         designation               description          productid    imageid
0  Olivia: Personalisier...                       NaN  3804725264  1263597046
1  Journal Des Arts (Le)...                       NaN   436067568  1008141237
2  Grand Stylet Ergonomi...  PILOT STYLE Touch Pen...   201115110   938777978
3  Peluche Donald - Euro...                       NaN    50418756   457047496
4      La Guerre Des Tuques  Luc a des id&eacute;e...   278535884  1077757786

In [17]:
modalite_X_train = pd.DataFrame({
    'colonne': X_train.columns,
    'nb_modalites_uniques': [X_train[col].nunique(dropna=False) for col in X_train.columns]
})

modalite_X_train.sort_values(by='nb_modalites_uniques', ascending=False)

    colonne     nb_modalites_uniques
0   Unnamed: 0          84916
4      imageid          84916
3    productid          84916
1  designation          82265
2  description          47507

In [23]:
print("Nombre de produits dans X_train est de:", len(X_train))

Nombre de produits dans X_train est de: 84916

In [20]:
modalite_X_test = pd.DataFrame({
    'colonne': X_test.columns,
    'nb_modalites_uniques': [X_test[col].nunique(dropna=False) for col in X_test.columns]
})

modalite_X_test.sort_values(by='nb_modalites_uniques', ascending=False)

    colonne     nb_modalites_uniques
0   Unnamed: 0          13812
4      imageid          13812
3    productid          13812
1  designation          13681
2  description           8347

In [26]:
print("Nombre de produits dans X_test est de:", len(X_test))
print("Nombre de produits dans la base Rakuten est de:", len(X_test) + len(X_train))

Nombre de produits dans X_test est de: 13812
Nombre de produits dans la base Rakuten est de: 98728

In [28]:
modalite_Y_train = pd.DataFrame({
    'colonne': Y_train.columns,
    'nb_modalites_uniques': [Y_train[col].nunique(dropna=False) for col in Y_train.columns]
})

modalite_Y_train.sort_values(by='nb_modalites_uniques', ascending=False)

    colonne     nb_modalites_uniques
0   Unnamed: 0          84916
1  prdtypecode             27

In [31]:
print("Nombre de catégories de produits dans Y_train est de:", Y_train["prdtypecode"].nunique())

Nombre de catégories de produits dans Y_train est de: 27